services:
  webserver:
    image: webserver
    volumes:
      - ./app
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports:
      - 5002:5002
  client:
    image: client
    volumes:
      - ./app
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
